#!/usr/bin/env bash
# script to install nginx on my web server

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t

sudo service nginx restart
