#!/usr/bin/env bash
#commands to perform a page redirection

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_redirect="server_name _;\n\trewrite ^\/redirect_me https\/\/github.com\/MthokozisiZwane permanent;"

sudo sed -i "s/server_name _;/$string_redirect/" /etc/nginx/sites-enabled/default

sudo service nginx restart
