#!/usr/bin/env bash
# configuring an HTTP header response for web-01/02

# updating packages
sudo apt-get update
sudo apt-get install -y nginx

# the index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# performing a redirection
string_redirect="server_name _;\\n\\trewrite ^\\/redirect_me https:\\/\\/github.com\\/MthokozisiZwane permanent;"
sudo sed -i "s|server_name _;|$string_redirect|" /etc/nginx/sites-enabled/default

# creating a custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# custom HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx
sudo systemctl restart nginx

