#!/usr/bin/env bash
# This script installs and configures HAProxy on lb-01 server

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get -y install haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend mthokozisi.tech_front
    bind *:80
    mode http
    default_backend mthokozisi.tech_back

backend mthokozisi.tech_back
    mode http
    balance roundrobin
    server web-01 52.86.97.136:80 check
    server web-02 52.3.243.60:80 check
EOF

# Restarting HAProxy
sudo service haproxy restart

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Display HAProxy status
sudo systemctl status haproxy

