#!/usr/bin/env bash
# This script answers questions related to UDP and TCP

# Which statement is correct for the TCP box:
 2

# Which statement is correct for the UDP box:
 1

# Which statement is correct for the TCP worker:
 2


