#!/usr/bin/env bash
# Displays a story based on the content of /etc/passwd using the while loop + IFS
while IFS=':' read -r username _ gid _ home shell; do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $gid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd

