#!/usr/bin/env bash
# The script configures localhost and the facebook.com IP addresses

# Backup of the hosts file
sudo cp /etc/hosts /etc/hosts_backup

# changing the hosts file
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts
sudo sed -i 's/facebook.com/8.8.8.8/' /etc/hosts

