#!/usr/bin/env bash
# This script configures localhost and facebook.com IP addresses

# Create a temporary hosts file
temp_hosts="/tmp/hosts_temp"
cp /etc/hosts "$temp_hosts"

# Modify the temporary file
sed -i 's/127.0.0.1/127.0.0.2/' "$temp_hosts"
sed -i 's/facebook.com/8.8.8.8/' "$temp_hosts"

# Replace the original hosts file with the modified temporary file
cp "$temp_hosts" /etc/hosts

# Cleanup: Removing the temporary file
rm "$temp_hosts"
