#!/usr/bin/env bash
# This script runs the 'whoami' command under the user passed as an argument

if [ "$#" -ne 1 ]; then #check if 1 argument is passed
    echo "Usage: $0 <username>"
    exit 1
fi

sudo -u "$1" whoami
