#!/usr/bin/env bash
# Configures Nginx to run as nginx user, listen on port 8080
sed -i 's/user .*;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen \(.*\)80;/listen 8080;/' /etc/nginx/sites-available/default
service nginx restart
ps auxff | grep ngin[x]
nc -z 0 8080
